In [4]:
import numpy as np

In [70]:
arr = [
    [2,4,10,7,9],
    [20,40,100,70,90]
]

arr = np.array(arr)
# shape ndim zeros dot ones empty random vastck hastack
np.shape(arr)

print(arr.ndim)

zeroArr = np.zeros((3,4))
print(zeroArr)

oneArr = np.ones((3,4))
print(oneArr)

emptArr = np.empty((3,4))
print(emptArr)

randArr = np.random.random((3,4))
print(randArr)

reshapeArr = np.reshape(arr, (5,2))
print(reshapeArr)

linspaceArr = np.linspace(1,10,10)
print(linspaceArr)

2
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.99745445 0.99667601 0.01220273 0.33355439]
 [0.89798125 0.09259117 0.84042122 0.57304385]
 [0.8209503  0.86464135 0.89090653 0.50275585]]
[[  2   4]
 [ 10   7]
 [  9  20]
 [ 40 100]
 [ 70  90]]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
